title: "Shrivats Mishra"
logo: /assets/MyPhoto.png
description: "Fullstack Developer | Data Analyst"
show_downloads: true
theme: jekyll-theme-minimal

# Customize navigation links
navigation_links:
  - title: Home
    url: /

# Social links
social_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/shrivats-mishra/
  - title: GitHub
    url: https://github.com/shrivatsam13
